INSERT INTO pets (age, name, kind) VALUES (10, 'john', 'dog');
INSERT INTO pets (age, name, kind) VALUES (12, 'frederick', 'cat');
INSERT INTO pets (age, name, kind) VALUES (15, 'samuel', 'lizard');
INSERT INTO pets (age, name, kind) VALUES (4, 'davey', 'parakeet');
INSERT INTO pets (age, name, kind) VALUES (8, 'spot', 'cow');
INSERT INTO pets (age, name, kind) VALUES (20, 'jim', 'cricket');
INSERT INTO pets (age, name, kind) VALUES (300, 'henry-adams', 'henry-adams');
INSERT INTO pets (age, name, kind) VALUES (80, 'cowlick', 'newt');
INSERT INTO pets (age, name, kind) VALUES (12, 'mr. bubbles', 'blastoise');
INSERT INTO pets (age, name, kind) VALUES (92, 'james francis', 'french');
INSERT INTO pets (age, name, kind) VALUES (10, 'kevin', 'penguin');
INSERT INTO pets (age, name, kind) VALUES (5, 'updog', 'down dog');
INSERT INTO pets (age, name, kind) VALUES (6, 'james adams', 'human');
INSERT INTO pets (age, name, kind) VALUES (13, 'killer', 'sinful');
INSERT INTO pets (age, name, kind) VALUES (1, 'sammy', 'fish');
INSERT INTO pets (age, name, kind) VALUES (88, 'hamster', 'hamster');
INSERT INTO pets (age, name, kind) VALUES (27, 'jane', 'not okay');
INSERT INTO pets (age, name, kind) VALUES (32, 'eli', 'youtuber');
INSERT INTO pets (age, name, kind) VALUES (3, 'man', 'animal');
INSERT INTO pets (age, name, kind) VALUES (4, 'elk', 'moose');
INSERT INTO pets (age, name, kind) VALUES (15, 'sefaaw', 'fawsee');
INSERT INTO pets (age, name, kind) VALUES (2, 'gilfurd', 'cat');
INSERT INTO pets (age, name, kind) VALUES (2, 'thomas', 'business-major');